"""Initial migration

Revision ID: f877b1c1e047
Revises: 
Create Date: 2025-04-12 09:40:19.019318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f877b1c1e047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participants', sa.Column('attendance_status', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('title', sa.String(length=255), server_default='未入力', nullable=False))
    op.add_column('events', sa.Column('max_participants', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'profile_picture')
    op.drop_column('events', 'is_public')
    op.drop_column('events', 'max_participants')
    op.drop_column('events', 'title')
    op.drop_column('event_participants', 'attendance_status')
    # ### end Alembic commands ###
